import { getParagonItem } from '../helpers/advancements.mjs';

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class DieRpgActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const systemData = actorData.system;
    // const flags = actorData.flags.dierpg || {};
    // const stats = systemData.stats;
    // const resources = systemData.resources;

    // Calculate initial Guard value based on Dexterity
    // resources.guard.value = stats.dex?.value ?? 0;

    // Calculate initial Health based on Constitution
    // resources.health.value = stats.con?.value ?? 0;

    // Calculate Willpower based on Wisdom + Intelligence
    // resources.willpower.value = (stats.wis?.value ?? 0) + (stats.int?.value ?? 0);

    // Calculate Defense (Base 0 + Items/Effects)
    // let defenseBonus = 0;
    // for (const item of this.items) {
    //   // TODO: Add check for equipped status if applicable
    //   if (item.type === 'equipment' && item.system?.defenseBonus) {
    //     defenseBonus += item.system.defenseBonus;
    //   }
    // }
    // Add bonuses from Active Effects if needed later
    // defenseBonus += activeEffectBonuses;

    // Set the final defense value (base is 0 from data model)
    // resources.defense.value = defenseBonus;

    // Ensure current values don't exceed new maximums (optional, but good practice)
    // resources.guard.value = Math.min(resources.guard.value, resources.guard.max);
    // resources.health.value = Math.min(resources.health.value, resources.health.max);
    // if (resources.willpower && systemData.willpowerMax !== undefined) {
    //   resources.willpower.value = Math.min(resources.willpower.value, systemData.willpowerMax);
    // }
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * Get all available specials from owned items and actor features.
   * Intelligently filters based on item type and state (equipped, active, etc.).
   *
   * @param {object} [options={}] Filtering options.
   * @param {boolean} [options.equipped=true] Include equipped equipment.
   * @param {boolean} [options.active=true] Include active stances/gifts.
   * @param {boolean} [options.paragon=true] Include paragon specials.
   * @param {string} [options.abilityId=null] Include specific ability's specials.
   * @returns {Array<object>} Array of special objects with source metadata.
   */
  getAvailableSpecials(options = {}) {
    const {
      equipped = true,
      active = true,
      paragon = true,
      abilityId = null
    } = options;

    const specials = [];

    // Helper to add specials with source info
    const addSpecials = (item, specialsList) => {
      if (!specialsList || specialsList.length === 0) return;

      specialsList.forEach(special => {
        specials.push({
          ...special,
          _source: {
            itemId: item.id,
            itemName: item.name,
            itemType: item.type,
            itemImg: item.img
          }
        });
      });
    };

    // 1. PARAGON: Always active (core class abilities)
    if (paragon) {
      const paragonItem = this.items.find(item => item.type === 'paragon');
      if (paragonItem?.system?.specials) {
        addSpecials(paragonItem, paragonItem.system.specials);
      }
    }

    // 2. EQUIPMENT: Always active (no equipped/unequipped concept in DIE RPG)
    if (equipped) {
      this.items
        .filter(item => item.type === 'equipment')
        .forEach(item => {
          addSpecials(item, item.system.specials);
        });
    }

    // 3. STANCES: Only if active
    if (active) {
      this.items
        .filter(item => item.type === 'stance' && item.system.active)
        .forEach(item => {
          addSpecials(item, item.system.specials);
        });
    }

    // 4. GIFTS: Only if activated
    if (active) {
      this.items
        .filter(item => item.type === 'gift' && item.system.activated)
        .forEach(item => {
          // Add gift's direct specials (if any)
          if (item.system.specials) {
            addSpecials(item, item.system.specials);
          }

          // Also add specials from gift upgrades
          if (item.system.upgrades) {
            item.system.upgrades.forEach(upgrade => {
              if (upgrade.specials && upgrade.specials.length > 0) {
                upgrade.specials.forEach(special => {
                  specials.push({
                    ...special,
                    _source: {
                      itemId: item.id,
                      itemName: `${item.name} (${upgrade.name})`,
                      itemType: 'gift',
                      itemImg: item.img
                    }
                  });
                });
              }
            });
          }
        });
    }

    // 5. GODS: Always active if contracted (Godbinder)
    this.items
      .filter(item => item.type === 'god')
      .forEach(item => {
        // Add specials from scriptures
        if (item.system.scriptures) {
          item.system.scriptures.forEach(scripture => {
            if (scripture.specials && scripture.specials.length > 0) {
              scripture.specials.forEach(special => {
                specials.push({
                  ...special,
                  _source: {
                    itemId: item.id,
                    itemName: `${item.name} (${scripture.name})`,
                    itemType: 'god',
                    itemImg: item.img
                  }
                });
              });
            }
          });
        }
      });

    // 6. SPELLS: Include if rolling for a specific spell
    if (abilityId) {
      const ability = this.items.get(abilityId);
      if (ability?.system?.specials) {
        addSpecials(ability, ability.system.specials);
      }
    }

    return specials;
  }

  /**
   * Get the paragon item for this actor.
   * @returns {Promise<DieRpgItem|null>} The found paragon item or null.
   * @protected
   */
  async _getClassDieItem() {
    return await getParagonItem(this);
  }
}
