/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class DieRpgActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    super.prepareDerivedData(); // Ensure upstream preparation runs if needed in the future.

    const systemData = this.system;
    const stats = systemData.stats;
    const resources = systemData.resources;

    // Calculate Max Guard based on Dexterity
    if (resources.guard) {
      resources.guard.max = stats.dex?.value ?? 0;
    }

    // Calculate Max Health based on Constitution
    if (resources.health) {
      resources.health.max = stats.con?.value ?? 0;
    }

    // Calculate Max Willpower based on Wisdom + Intelligence
    // Note: Willpower doesn't have a 'max' in the current base model, only 'value'.
    // If a max is needed later, it should be added to base-actor.mjs.
    // For now, we'll calculate a potential max value if needed elsewhere.
    // systemData.willpowerMax = (stats.wis?.value ?? 0) + (stats.int?.value ?? 0);

    // Calculate Defense (Base 0 + Items/Effects)
    let defenseBonus = 0;
    for (const item of this.items) {
      // TODO: Add check for equipped status if applicable
      if (item.type === 'gear' && item.system?.defenseBonus) {
        defenseBonus += item.system.defenseBonus;
      }
    }
    // Add bonuses from Active Effects if needed later
    // defenseBonus += activeEffectBonuses;

    // Set the final defense value (base is 0 from data model)
    resources.defense.value = defenseBonus;

    // Ensure current values don't exceed new maximums (optional, but good practice)
    if (resources.guard) {
      resources.guard.value = Math.min(resources.guard.value, resources.guard.max);
    }
    if (resources.health) {
      resources.health.value = Math.min(resources.health.value, resources.health.max);
    }
    // if (resources.willpower && systemData.willpowerMax !== undefined) {
    //   resources.willpower.value = Math.min(resources.willpower.value, systemData.willpowerMax);
    // }
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * Find the first equipped item of type 'class' on the actor.
   * @returns {DieRpgItem|null} The found class item or null.
   * @protected
   */
  _getClassDieItem() {
    // TODO: Add check for 'equipped' status if applicable
    return this.items.find(item => item.type === 'class');
  }
}
